### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by rshipp** [julianbrowne/dijkstra#1]
Hi! Would you consider adding a [LICENSE](http://choosealicense.com/) file to the repository? The [default is full copyright](http://choosealicense.com/no-license/), which means no one can use it. Thanks!

**Comment by julianbrowne** [comment]
Thanks. Good spot. I've added an MIT license. 

This also applies to the other shortest-path related repos:

https://github.com/julianbrowne/dijkstra-explorer  
https://github.com/julianbrowne/shortest-path-d3-mapper-example  
https://github.com/julianbrowne/shortest-path-d3-router-example  

I will update these too.
